### ISSUE TITLE
Missing libs

### ISSUE THREAD

**Issue by SteveSmith16384** [HaveANiceDay33/zoomzoom#1]
Hi, I tried building your game, but there are missing libs: Ridhvl, HVOL-B and HVOL-Direct.  Would you be able to include them?

**Comment by osreboot** [comment]
Hi Steve, thanks for showing interest in our project!

Ridhvl is open-source and can be found [here](https://github.com/osreboot/Ridhvl). All you need to do is clone the project and make sure it's in the workspace with this one.

As for the other two dependencies - I actually haven't made the code public so as to protect the integrity of game servers that are built using them. For the sake of this project, I've attached the compiled versions of these dependencies as JARs and updated their references. You should be able to compile our game now.

We use the main method in com.samuel.Main to launch both the server and client, you just need to uncomment either line 16 or 18 depending on which one you want to run.

**Comment by SteveSmith16384** [comment]
Thanks for the reply, I'll have a go.
